export type User = {
  id: number;
  name: string;
  email: string;
  role: string;
};

export const users: User[] = [
  {
    id: 1,
    name: "Anna Nowak",
    email: "anna@example.com",
    role: "admin",
  },
  {
    id: 2,
    name: "Jan Kowalski",
    email: "jan@example.com",
    role: "user",
  },
  {
    id: 3,
    name: "Kasia Wiśniewska",
    email: "kasia@example.com",
    role: "user",
  },
  {
    id: 4,
    name: "Tomasz Malinowski",
    email: "tomasz@example.com",
    role: "owner",
  },
  {
    id: 5,
    name: "Adam Kowalski",
    email: "adam.kowalski@example.com",
    role: "user",
  },
  {
    id: 6,
    name: "Ewa Nowak",
    email: "ewa.nowak@example.com",
    role: "admin",
  },
  {
    id: 7,
    name: "Marek Wiśniewski",
    email: "marek.wisniewski@example.com",
    role: "user",
  },
  {
    id: 8,
    name: "Ola Wójcik",
    email: "ola.wojcik@example.com",
    role: "owner",
  },
  {
    id: 9,
    name: "Piotr Kowalczyk",
    email: "piotr.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 10,
    name: "Magda Kamiński",
    email: "magda.kaminski@example.com",
    role: "admin",
  },
  {
    id: 11,
    name: "Bartek Lewandowski",
    email: "bartek.lewandowski@example.com",
    role: "user",
  },
  {
    id: 12,
    name: "Zosia Zieliński",
    email: "zosia.zielinski@example.com",
    role: "user",
  },
  {
    id: 13,
    name: "Kuba Szymański",
    email: "kuba.szymanski@example.com",
    role: "owner",
  },
  {
    id: 14,
    name: "Basia Woźniak",
    email: "basia.wozniak@example.com",
    role: "user",
  },
  {
    id: 15,
    name: "Adam Nowak",
    email: "adam.nowak@example.com",
    role: "user",
  },
  {
    id: 16,
    name: "Ewa Kowalski",
    email: "ewa.kowalski@example.com",
    role: "admin",
  },
  {
    id: 17,
    name: "Marek Wójcik",
    email: "marek.wojcik@example.com",
    role: "user",
  },
  {
    id: 18,
    name: "Ola Kowalczyk",
    email: "ola.kowalczyk@example.com",
    role: "owner",
  },
  {
    id: 19,
    name: "Piotr Kamiński",
    email: "piotr.kaminski@example.com",
    role: "user",
  },
  {
    id: 20,
    name: "Magda Lewandowski",
    email: "magda.lewandowski@example.com",
    role: "admin",
  },
  {
    id: 21,
    name: "Bartek Zieliński",
    email: "bartek.zielinski@example.com",
    role: "user",
  },
  {
    id: 22,
    name: "Zosia Szymański",
    email: "zosia.szymanski@example.com",
    role: "user",
  },
  {
    id: 23,
    name: "Kuba Woźniak",
    email: "kuba.wozniak@example.com",
    role: "owner",
  },
  {
    id: 24,
    name: "Basia Kowalski",
    email: "basia.kowalski@example.com",
    role: "user",
  },
  {
    id: 25,
    name: "Adam Wiśniewski",
    email: "adam.wisniewski@example.com",
    role: "user",
  },
  {
    id: 26,
    name: "Ewa Wójcik",
    email: "ewa.wojcik@example.com",
    role: "admin",
  },
  {
    id: 27,
    name: "Marek Kowalczyk",
    email: "marek.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 28,
    name: "Ola Kamiński",
    email: "ola.kaminski@example.com",
    role: "owner",
  },
  {
    id: 29,
    name: "Piotr Lewandowski",
    email: "piotr.lewandowski@example.com",
    role: "user",
  },
  {
    id: 30,
    name: "Magda Zieliński",
    email: "magda.zielinski@example.com",
    role: "admin",
  },
  {
    id: 31,
    name: "Bartek Szymański",
    email: "bartek.szymanski@example.com",
    role: "user",
  },
  {
    id: 32,
    name: "Zosia Woźniak",
    email: "zosia.wozniak@example.com",
    role: "user",
  },
  {
    id: 33,
    name: "Kuba Nowak",
    email: "kuba.nowak@example.com",
    role: "owner",
  },
  {
    id: 34,
    name: "Basia Kowalski",
    email: "basia.kowalski2@example.com",
    role: "user",
  },
  {
    id: 35,
    name: "Adam Wójcik",
    email: "adam.wojcik@example.com",
    role: "user",
  },
  {
    id: 36,
    name: "Ewa Kowalczyk",
    email: "ewa.kowalczyk@example.com",
    role: "admin",
  },
  {
    id: 37,
    name: "Marek Kamiński",
    email: "marek.kaminski@example.com",
    role: "user",
  },
  {
    id: 38,
    name: "Ola Lewandowski",
    email: "ola.lewandowski@example.com",
    role: "owner",
  },
  {
    id: 39,
    name: "Piotr Zieliński",
    email: "piotr.zielinski@example.com",
    role: "user",
  },
  {
    id: 40,
    name: "Magda Szymański",
    email: "magda.szymanski@example.com",
    role: "admin",
  },
  {
    id: 41,
    name: "Bartek Woźniak",
    email: "bartek.wozniak@example.com",
    role: "user",
  },
  {
    id: 42,
    name: "Zosia Kowalski",
    email: "zosia.kowalski@example.com",
    role: "user",
  },
  {
    id: 43,
    name: "Kuba Wiśniewski",
    email: "kuba.wisniewski@example.com",
    role: "owner",
  },
  {
    id: 44,
    name: "Basia Wójcik",
    email: "basia.wojcik@example.com",
    role: "user",
  },
  {
    id: 45,
    name: "Adam Kowalczyk",
    email: "adam.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 46,
    name: "Ewa Kamiński",
    email: "ewa.kaminski@example.com",
    role: "admin",
  },
  {
    id: 47,
    name: "Marek Lewandowski",
    email: "marek.lewandowski@example.com",
    role: "user",
  },
  {
    id: 48,
    name: "Ola Zieliński",
    email: "ola.zielinski@example.com",
    role: "owner",
  },
  {
    id: 49,
    name: "Piotr Szymański",
    email: "piotr.szymanski@example.com",
    role: "user",
  },
  {
    id: 50,
    name: "Magda Woźniak",
    email: "magda.wozniak@example.com",
    role: "admin",
  },
  {
    id: 51,
    name: "Bartek Nowak",
    email: "bartek.nowak@example.com",
    role: "user",
  },
  {
    id: 52,
    name: "Zosia Kowalski",
    email: "zosia.kowalski2@example.com",
    role: "user",
  },
  {
    id: 53,
    name: "Kuba Wójcik",
    email: "kuba.wojcik@example.com",
    role: "owner",
  },
  {
    id: 54,
    name: "Basia Kowalczyk",
    email: "basia.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 55,
    name: "Adam Kamiński",
    email: "adam.kaminski@example.com",
    role: "user",
  },
  {
    id: 56,
    name: "Ewa Lewandowski",
    email: "ewa.lewandowski@example.com",
    role: "admin",
  },
  {
    id: 57,
    name: "Marek Zieliński",
    email: "marek.zielinski@example.com",
    role: "user",
  },
  {
    id: 58,
    name: "Ola Szymański",
    email: "ola.szymanski@example.com",
    role: "owner",
  },
  {
    id: 59,
    name: "Piotr Woźniak",
    email: "piotr.wozniak@example.com",
    role: "user",
  },
  {
    id: 60,
    name: "Magda Kowalski",
    email: "magda.kowalski@example.com",
    role: "admin",
  },
  {
    id: 61,
    name: "Bartek Wiśniewski",
    email: "bartek.wisniewski@example.com",
    role: "user",
  },
  {
    id: 62,
    name: "Zosia Wójcik",
    email: "zosia.wojcik2@example.com",
    role: "user",
  },
  {
    id: 63,
    name: "Kuba Kowalczyk",
    email: "kuba.kowalczyk@example.com",
    role: "owner",
  },
  {
    id: 64,
    name: "Basia Kamiński",
    email: "basia.kaminski@example.com",
    role: "user",
  },
  {
    id: 65,
    name: "Adam Lewandowski",
    email: "adam.lewandowski@example.com",
    role: "user",
  },
  {
    id: 66,
    name: "Ewa Zieliński",
    email: "ewa.zielinski@example.com",
    role: "admin",
  },
  {
    id: 67,
    name: "Marek Szymański",
    email: "marek.szymanski@example.com",
    role: "user",
  },
  {
    id: 68,
    name: "Ola Woźniak",
    email: "ola.wozniak2@example.com",
    role: "owner",
  },
  {
    id: 69,
    name: "Piotr Nowak",
    email: "piotr.nowak@example.com",
    role: "user",
  },
  {
    id: 70,
    name: "Magda Kowalski",
    email: "magda.kowalski2@example.com",
    role: "admin",
  },
  {
    id: 71,
    name: "Bartek Wójcik",
    email: "bartek.wojcik2@example.com",
    role: "user",
  },
  {
    id: 72,
    name: "Zosia Kowalczyk",
    email: "zosia.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 73,
    name: "Kuba Kamiński",
    email: "kuba.kaminski@example.com",
    role: "owner",
  },
  {
    id: 74,
    name: "Basia Lewandowski",
    email: "basia.lewandowski@example.com",
    role: "user",
  },
  {
    id: 75,
    name: "Adam Zieliński",
    email: "adam.zielinski@example.com",
    role: "user",
  },
  {
    id: 76,
    name: "Ewa Szymański",
    email: "ewa.szymanski@example.com",
    role: "admin",
  },
  {
    id: 77,
    name: "Marek Woźniak",
    email: "marek.wozniak@example.com",
    role: "user",
  },
  {
    id: 78,
    name: "Ola Nowak",
    email: "ola.nowak@example.com",
    role: "owner",
  },
  {
    id: 79,
    name: "Piotr Kowalski",
    email: "piotr.kowalski@example.com",
    role: "user",
  },
  {
    id: 80,
    name: "Magda Wiśniewski",
    email: "magda.wisniewski@example.com",
    role: "admin",
  },
  {
    id: 81,
    name: "Bartek Wójcik",
    email: "bartek.wojcik3@example.com",
    role: "user",
  },
  {
    id: 82,
    name: "Zosia Kamiński",
    email: "zosia.kaminski@example.com",
    role: "user",
  },
  {
    id: 83,
    name: "Kuba Lewandowski",
    email: "kuba.lewandowski@example.com",
    role: "owner",
  },
  {
    id: 84,
    name: "Basia Zieliński",
    email: "basia.zielinski@example.com",
    role: "user",
  },
  {
    id: 85,
    name: "Adam Szymański",
    email: "adam.szymanski@example.com",
    role: "user",
  },
  {
    id: 86,
    name: "Ewa Woźniak",
    email: "ewa.wozniak@example.com",
    role: "admin",
  },
  {
    id: 87,
    name: "Marek Nowak",
    email: "marek.nowak@example.com",
    role: "user",
  },
  {
    id: 88,
    name: "Ola Kowalski",
    email: "ola.kowalski@example.com",
    role: "owner",
  },
  {
    id: 89,
    name: "Piotr Wiśniewski",
    email: "piotr.wisniewski@example.com",
    role: "user",
  },
  {
    id: 90,
    name: "Magda Wójcik",
    email: "magda.wojcik@example.com",
    role: "admin",
  },
  {
    id: 91,
    name: "Bartek Kowalczyk",
    email: "bartek.kowalczyk@example.com",
    role: "user",
  },
  {
    id: 92,
    name: "Zosia Kamiński",
    email: "zosia.kaminski2@example.com",
    role: "user",
  },
  {
    id: 93,
    name: "Kuba Lewandowski",
    email: "kuba.lewandowski2@example.com",
    role: "owner",
  },
  {
    id: 94,
    name: "Basia Zieliński",
    email: "basia.zielinski2@example.com",
    role: "user",
  },
  {
    id: 95,
    name: "Adam Szymański",
    email: "adam.szymanski2@example.com",
    role: "user",
  },
  {
    id: 96,
    name: "Ewa Woźniak",
    email: "ewa.wozniak2@example.com",
    role: "admin",
  },
  {
    id: 97,
    name: "Marek Nowak",
    email: "marek.nowak2@example.com",
    role: "user",
  },
  {
    id: 98,
    name: "Ola Kowalski",
    email: "ola.kowalski2@example.com",
    role: "owner",
  },
  {
    id: 99,
    name: "Piotr Wiśniewski",
    email: "piotr.wisniewski2@example.com",
    role: "user",
  },
  {
    id: 100,
    name: "Magda Wójcik",
    email: "magda.wojcik2@example.com",
    role: "admin",
  },
];
